repos:
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.0.0
    hooks:
      - id: prettier
        files: \.(bib|json|yaml)$

  - repo: local
    hooks:
      - id: latexmk-clean
        name: Cleanup LaTeX build files with latexmk
        entry: bash -c 'latexmk -c && find . -name "*.synctex.gz" -delete'
        language: system
        types: [tex]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
